# Generated by BanglaLang Compiler
# Target: Python 3

# সংখ্যা a
a = 10
# সংখ্যা b
b = 3
# দশমিক result
result = ((a + (b * 2)) / 4)
print(result)
if (a > b):
    print(a)
else:
    print(b)
while (b > 0):
    b = (b - 1)
    print(b)
