# Generated by BanglaLang Compiler
# Target: Python 3

# সংখ্যা x
x = 10
# সংখ্যা y
y = 5
# দশমিক average
average = ((x + y) / 2)
print(average)
if (x > y):
    print(x)
else:
    print(y)
while (x > 6):
    x = (x - 1)
    print(x)
